[package]
name = "alloy-zksync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-consensus = "0.1.2"
alloy-eips = { version = "0.4.0", features = ["serde"] }
alloy-network = "0.1.2"
alloy-primitives = { version = "0.7.6", features = ["std", "k256", "serde"] }
alloy-rlp = "0.3.8"
alloy-rpc-types-eth = "0.1.2"
alloy-serde = "0.3.6"
alloy-signer = { version = "0.1.3", features = ["eip712"] }
alloy-sol-types = "0.7"
async-trait = "0.1.80"
futures-utils-wasm = "0.1.0"
k256 = "0.13.3"
rand = "0.8.5"
serde = "1.0.203"
thiserror = "1.0.61"
tracing = "0.1.40"
url = "2.5.2"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
alloy = { version = "0.1", features = ["network", "providers", "signers", "signer-local"] }
hex = "0.4.3"
assert_matches = "1.5.0"
